CFLAGS+=" $(pkg-config --cflags harfbuzz)"
OPTS+=" -DCMAKE_POLICY_VERSION_MINIMUM=3.5 \
        -DINSTALL_CMAKE_MODULESDIR=/usr/share/libgaminggear/cmake/Modules \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DINSTALL_LIBDIR=/usr/lib"

default_cmake_build
